[package]
name = "pit-core"
version = "0.4.9"
edition = "2024"
license = "CC0-1.0"
description = "Portal Interface Types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
derive_more = { version = "2", default-features = false, features = ["display"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
instability = "0.3.7"
nom = { version = "8", default-features = false, features = ["alloc"] }
sha3 = { version = "0.10.8", default-features = false }

[features]
unstable-pcode=[]
unstable-generics=[]
